repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
      - id: mypy

  - repo: local
    hooks:
      - id: run-pytest
        name: Run Pytest
        entry: poetry run pytest tests/
        language: system
        types: [ python ]
        pass_filenames: false